# Generated by Django 5.2.10 on 2026-04-05 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_router", "0001_initial"),
        ("ai_agents", "0015_remove_llmlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="llmlog",
            new_name="ai_router_l_agent_n_657da1_idx",
            old_name="ai_agents_l_agent_n_9be473_idx",
        ),
        migrations.RenameIndex(
            model_name="llmlog",
            new_name="ai_router_l_created_eba8ee_idx",
            old_name="ai_agents_l_created_05b6c3_idx",
        ),
        migrations.AlterModelTable(
            name="llmlog",
            table=None,
        ),
    ]
