# Generated by Django 5.2.10 on 2026-04-05 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_router", "0002_rename_table_and_indexes"),
    ]

    operations = [
        migrations.AddField(
            model_name="llmlog",
            name="cache_creation_input_tokens",
            field=models.IntegerField(blank=True, help_text="Tokens neu in den Prompt-Cache geschrieben", null=True),
        ),
        migrations.AddField(
            model_name="llmlog",
            name="cache_read_input_tokens",
            field=models.IntegerField(blank=True, help_text="Tokens aus dem Prompt-Cache gelesen", null=True),
        ),
    ]
