# Generated by Django 5.2.10 on 2026-06-01 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ai_router", "0003_add_cache_token_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="llmlog",
            name="retry_count",
        ),
    ]
